{% set version = "0.6.6" %}

package:
  name: rav1e
  version: {{ version }}

source:
  url: https://github.com/xiph/rav1e/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 723696e93acbe03666213fbc559044f3cae5b8b888b2ddae667402403cff51e5

build:
  number: 1
  run_exports:
    # It seems that they export a so with .0, so I'm going to wish for the best
    - {{ pin_subpackage('rav1e', max_pin='x') }}
  ignore_run_exports:
    # Need to include it for cargo-c to be installed
    - openssl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - nasm
    - cargo-bundle-licenses
    - pkg-config                         # [unix]
  host:
    - openssl

test:
  commands:
    - rav1e --help
    - test -f ${PREFIX}/lib/librav1e${SHLIB_EXT}             # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\rav1e.dll exit 1   # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\rav1e.lib exit 1   # [win]

about:
  home: https://github.com/xiph/rav1e
  summary: The fastest and safest AV1 encoder.
  description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use
    cases, though in its current form it is most suitable for cases where
    libaom (the reference encoder) is too slow.
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - hmaarrfk
